#!/usr/bin/env bash
# Writes THIRD_PARTY_NOTICES.md: the licence text of every module compiled
# into shoal, and of the Go standard library, which the MIT and BSD
# licences they carry ask to accompany any copy of the binary. Run by
# `make notices`, and by `make release` before packaging.
set -euo pipefail

GO=${GO:-go}
out=${1:-THIRD_PARTY_NOTICES.md}
goroot=$("$GO" env GOROOT)
goversion=$("$GO" env GOVERSION)

licence_files() {
	# Everything that is a licence, notice or patent grant; not AUTHORS
	# lists or READMEs.
	find "$1" -maxdepth 1 -type f \( -iname 'licen[cs]e*' -o -iname 'copying*' -o -iname 'notice*' -o -iname 'patents*' \) | sort
}

section() { # title, version, directory
	echo "## $1 $2"
	echo
	local found=0
	while IFS= read -r f; do
		[ -n "$f" ] || continue
		found=1
		echo "### $(basename "$f")"
		echo
		echo '```'
		cat "$f"
		echo '```'
		echo
	done < <(licence_files "$3")
	if [ "$found" = 0 ]; then
		echo "No licence file found in the module; see its source."
		echo
	fi
}

{
	echo "# Third-party notices"
	echo
	echo "shoal is distributed under the MIT licence in LICENSE. The binary also"
	echo "contains the software below, each under its own licence, reproduced here"
	echo "as those licences require. Generated by scripts/third-party-notices.sh;"
	echo "do not edit by hand."
	echo
	echo "The embedded vendor list, data/oui.csv, is the IEEE Registration"
	echo "Authority's public MA-L listing, from https://standards-oui.ieee.org/."
	echo
	section "The Go standard library" "$goversion" "$goroot"
	"$GO" list -deps -f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}' ./cmd/shoal |
		sort -u |
		while read -r path version dir; do
			section "$path" "$version" "$dir"
		done
} > "$out"
echo "wrote $out"
