#!/usr/bin/env bash
# Writes THIRD_PARTY_NOTICES.md: the licence text of every module compiled
# into shoal, and of the Go standard library, which the MIT and BSD
# licences they carry ask to accompany any copy of the binary. Run by
# `make notices`, and by `make release` before packaging.
set -euo pipefail

GO=${GO:-go}
out=${1:-THIRD_PARTY_NOTICES.md}
# The release platforms; `make notices` passes the Makefile's list.
PLATFORMS=${PLATFORMS:-linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 freebsd/amd64}
goroot=$("$GO" env GOROOT)
goversion=$("$GO" env GOVERSION)

# The Go licence has to be in here: these notices accompany a distributed
# binary, and shipping them without it is worse than not building at all.
# It is not always inside GOROOT — Homebrew puts it one level up — so both
# are searched, and a miss stops the build rather than passing quietly.
# Before this check, `make release` once wrote notices carrying Go's PATENTS
# file and no LICENSE, and said nothing.
require_go_licence() {
	local f
	for f in "$goroot"/* "$goroot"/../*; do
		case "$(basename "$f" 2>/dev/null)" in
		[Ll][Ii][Cc][Ee][Nn][SsCc][Ee]*) [ -f "$f" ] && return 0 ;;
		esac
	done
	echo "third-party-notices: no Go licence file in $goroot or its parent;" >&2
	echo "  the notices would ship incomplete, so nothing was written." >&2
	exit 1
}
require_go_licence

licence_files() {
	# Everything that is a licence, notice or patent grant; not AUTHORS
	# lists or READMEs. Several directories may be given: Homebrew keeps the
	# Go licence beside GOROOT rather than inside it.
	find "$@" -maxdepth 1 -type f \( -iname 'licen[cs]e*' -o -iname 'copying*' -o -iname 'notice*' -o -iname 'patents*' \) 2>/dev/null | sort -u
}

section() { # title, version, directory...
	local title=$1 version=$2
	shift 2
	echo "## $title $version"
	echo
	local found=0 seen=" "
	while IFS= read -r f; do
		[ -n "$f" ] || continue
		local base
		base=$(basename "$f")
		case "$seen" in *" $base "*) continue ;; esac
		seen="$seen$base "
		found=1
		echo "### $base"
		echo
		echo '```'
		cat "$f"
		echo '```'
		echo
	done < <(licence_files "$@")
	if [ "$found" = 0 ]; then
		echo "No licence file found in the module; see its source."
		echo
	fi
}

{
	echo "# Third-party notices"
	echo
	echo "shoal is distributed under the MIT licence in LICENSE. The binary also"
	echo "contains the software below, each under its own licence, reproduced here"
	echo "as those licences require. Generated by scripts/third-party-notices.sh;"
	echo "do not edit by hand."
	echo
	echo "The embedded vendor list, data/oui.csv, is the IEEE Registration"
	echo "Authority's public MA-L listing, from https://standards-oui.ieee.org/."
	echo
	section "The Go standard library" "$goversion" "$goroot" "$goroot/.."
	# Every platform a release builds, not just this one: modules differ by
	# platform (the SQLite driver pulls one in on macOS and FreeBSD only), and
	# one notices file goes into every archive. Listed on Linux alone, the
	# macOS archives once went out a licence short.
	for p in $PLATFORMS; do
		CGO_ENABLED=0 GOOS=${p%/*} GOARCH=${p#*/} "$GO" list -deps -f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}' ./cmd/shoal
	done |
		sort -u |
		while read -r path version dir; do
			section "$path" "$version" "$dir"
		done
} > "$out"
echo "wrote $out"
